repos:
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: bash -c "pytest"
        language: system
  - repo: https://github.com/psf/black
    rev: 19.10b0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''  # Use the sha / tag you want to point at
    hooks:
      - id: mypy